# Generated by Django 3.2.8 on 2022-02-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='fri_noon',
            field=models.IntegerField(default=0, verbose_name='שישי צהריים'),
        ),
    ]
