# Generated by Django 3.2.8 on 2022-02-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220214_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='image',
            field=models.TextField(default='', verbose_name='תמונה'),
        ),
    ]
