# Generated by Django 3.2.8 on 2022-02-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usersettings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='image',
            field=models.TextField(blank=True, default='', verbose_name='תמונה'),
        ),
    ]
