# Generated by Django 3.2.8 on 2022-02-07 13:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arming_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='שם')),
                ('id_num', models.CharField(default='', max_length=9, verbose_name='תעודת זהות')),
                ('shift_num', models.IntegerField(default=1, verbose_name='מספר משמרת')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='תאריך')),
                ('time_in', models.TimeField(default=django.utils.timezone.now, verbose_name='זמן כניסה')),
                ('num_mags', models.IntegerField(default=2, verbose_name='מספר מחסניות')),
                ('hand_cuffs', models.IntegerField(default=6, verbose_name='אזיקים')),
                ('gun_case', models.IntegerField(default=6, verbose_name='פונדה')),
                ('mag_case', models.IntegerField(default=6, verbose_name='נרתיק')),
                ('keys', models.BooleanField(default=False, verbose_name='מפתחות')),
                ('radio', models.BooleanField(default=False, verbose_name='קשר')),
                ('radio_kit', models.BooleanField(default=False, verbose_name='ערכת שמע')),
                ('time_out', models.TimeField(blank=True, null=True, verbose_name='זמן יציאה')),
                ('valid_in', models.TextField(blank=True, null=True, verbose_name='חתימת מנהל כניסה')),
                ('valid_out', models.TextField(blank=True, null=True, verbose_name='חתימת מנהל יציאה')),
                ('signature_in', models.TextField(blank=True, null=True, verbose_name='חתימת כניסה')),
                ('signature_out', models.TextField(blank=True, null=True, verbose_name='חתימת יציאה')),
            ],
            options={
                'verbose_name': 'הזנה ביומן חימוש',
                'verbose_name_plural': 'הזנות ביומן חימוש',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=20, verbose_name='כינוי')),
                ('date2', models.DateField(default=django.utils.timezone.now, verbose_name='תאריך')),
                ('description', models.CharField(default='', max_length=50, verbose_name='תאור')),
                ('training', models.BooleanField(default=False, verbose_name='חד יומי')),
                ('night_before', models.BooleanField(default=False, verbose_name='לילה יום לפני')),
                ('morning', models.BooleanField(default=False, verbose_name='בוקר')),
                ('after_noon', models.BooleanField(default=False, verbose_name='צהריים')),
                ('night', models.BooleanField(default=False, verbose_name='לילה')),
            ],
            options={
                'verbose_name': 'אירוע',
                'verbose_name_plural': 'אירועים',
            },
        ),
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='שם מלא')),
                ('short_name', models.CharField(max_length=20, verbose_name='שם קצר')),
            ],
            options={
                'verbose_name': 'נשק',
                'verbose_name_plural': 'נשקים',
            },
        ),
        migrations.CreateModel(
            name='IpBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='כתובת IP')),
                ('num_tries', models.IntegerField(default=0, verbose_name='מספר ניסיונות')),
            ],
            options={
                'verbose_name': 'חסימת IP',
                'verbose_name_plural': 'חסימות IP',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('num_weeks', models.IntegerField(default=2)),
                ('published', models.BooleanField(default=False, verbose_name='פרסום')),
            ],
            options={
                'verbose_name': 'סידור עבודה',
                'verbose_name_plural': 'סידורי עבודה',
            },
        ),
        migrations.CreateModel(
            name='OrganizationShifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='משמרת')),
                ('shift_num', models.IntegerField(default=1, verbose_name='סוג משמרת')),
                ('sub_title', models.CharField(max_length=200, verbose_name='כותרת משמרת')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitting', models.BooleanField(default=True, verbose_name='ניתן להגיש/לשנות הגשות')),
                ('pin_code', models.IntegerField(default=1234, verbose_name='קוד זיהוי')),
                ('officer', models.CharField(max_length=20, verbose_name='קצין מתקן')),
                ('city', models.CharField(max_length=100, verbose_name='עיר')),
                ('max_seq0', models.IntegerField(default=2, verbose_name='מספר רצפים מקסימלי לילה לצהריים')),
                ('max_seq1', models.IntegerField(default=2, verbose_name='מספר רצפים מקסימלי צהריים לבוקר')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='גרסה')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='תאריך')),
                ('num_guns_safe_m', models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים בכספת בוקר')),
                ('num_guns_shift_m', models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים במשמרת בוקר')),
                ('time_checked_m', models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='שעת בדיקה בוקר')),
                ('name_checked_m', models.CharField(blank=True, default='', max_length=50, verbose_name='שם בודק בוקר')),
                ('sig_m', models.TextField(blank=True, null=True, verbose_name='חתימה בוקר')),
                ('num_guns_safe_a', models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים בכספת צהריים')),
                ('num_guns_shift_a', models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים במשמרת צהריים')),
                ('time_checked_a', models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='שעת בדיקה צהריים')),
                ('name_checked_a', models.CharField(blank=True, default='', max_length=50, verbose_name='שם בודק צהריים')),
                ('sig_a', models.TextField(blank=True, null=True, verbose_name='חתימה צהריים')),
                ('num_guns_safe_n', models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים בכספת לילה')),
                ('num_guns_shift_n', models.IntegerField(blank=True, default=0, verbose_name='מספר נשקים במשמרת לילה')),
                ('time_checked_n', models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='שעת בדיקה לילה')),
                ('name_checked_n', models.CharField(blank=True, default='', max_length=50, verbose_name='שם בודק לילה')),
                ('sig_n', models.TextField(blank=True, null=True, verbose_name='חתימה לילה')),
            ],
            options={
                'verbose_name': 'בדיקת נשקים',
                'verbose_name_plural': 'בדיקות נשקים',
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2022, 2, 7, 13, 32, 49, 970031, tzinfo=utc))),
                ('num_week', models.IntegerField(default=0)),
                ('shifts', jsonfield.fields.JSONField()),
            ],
            options={
                'verbose_name': 'שבוע סידור',
                'verbose_name_plural': 'שבועות סידור',
            },
        ),
        migrations.CreateModel(
            name='ShiftWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_week', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('M1', models.BooleanField(default=False, verbose_name='ראשון בוקר')),
                ('A1', models.BooleanField(default=False, verbose_name='ראשון צהריים')),
                ('N1', models.BooleanField(default=False, verbose_name='ראשון לילה')),
                ('P1', models.BooleanField(default=True, verbose_name='משיכה')),
                ('R1', models.BooleanField(default=False, verbose_name='תגבור')),
                ('notes1', models.CharField(blank=True, max_length=100, verbose_name='הערות')),
                ('M2', models.BooleanField(default=False, verbose_name='שני בוקר')),
                ('A2', models.BooleanField(default=False, verbose_name='שני צהריים')),
                ('N2', models.BooleanField(default=False, verbose_name='שני לילה')),
                ('P2', models.BooleanField(default=True, verbose_name='משיכה')),
                ('R2', models.BooleanField(default=False, verbose_name='תגבור')),
                ('notes2', models.CharField(blank=True, max_length=100, verbose_name='הערות')),
                ('M3', models.BooleanField(default=False, verbose_name='שלישי בוקר')),
                ('A3', models.BooleanField(default=False, verbose_name='שלישי צהריים')),
                ('N3', models.BooleanField(default=False, verbose_name='שלישי לילה')),
                ('P3', models.BooleanField(default=True, verbose_name='משיכה')),
                ('R3', models.BooleanField(default=False, verbose_name='תגבור')),
                ('notes3', models.CharField(blank=True, max_length=100, verbose_name='הערות')),
                ('M4', models.BooleanField(default=False, verbose_name='רביעי בוקר')),
                ('A4', models.BooleanField(default=False, verbose_name='רביעי צהריים')),
                ('N4', models.BooleanField(default=False, verbose_name='רביעי לילה')),
                ('P4', models.BooleanField(default=True, verbose_name='משיכה')),
                ('R4', models.BooleanField(default=False, verbose_name='תגבור')),
                ('notes4', models.CharField(blank=True, max_length=100, verbose_name='הערות')),
                ('M5', models.BooleanField(default=False, verbose_name='חמישי בוקר')),
                ('A5', models.BooleanField(default=False, verbose_name='חמישי צהריים')),
                ('N5', models.BooleanField(default=False, verbose_name='חמישי לילה')),
                ('P5', models.BooleanField(default=True, verbose_name='משיכה')),
                ('R5', models.BooleanField(default=False, verbose_name='תגבור')),
                ('notes5', models.CharField(blank=True, max_length=100, verbose_name='הערות')),
                ('M6', models.BooleanField(default=False, verbose_name='שישי בוקר')),
                ('A6', models.BooleanField(default=False, verbose_name='שישי צהריים')),
                ('N6', models.BooleanField(default=False, verbose_name='שישי לילה')),
                ('P6', models.BooleanField(default=True, verbose_name='משיכה')),
                ('R6', models.BooleanField(default=False, verbose_name='תגבור')),
                ('notes6', models.CharField(blank=True, max_length=100, verbose_name='הערות')),
                ('M7', models.BooleanField(default=False, verbose_name='שבצ בוקר')),
                ('A7', models.BooleanField(default=False, verbose_name='שבת צהריים')),
                ('N7', models.BooleanField(default=False, verbose_name='שבת לילה')),
                ('P7', models.BooleanField(default=True, verbose_name='משיכה')),
                ('R7', models.BooleanField(default=False, verbose_name='תגבור')),
                ('notes7', models.CharField(blank=True, max_length=100, verbose_name='הערות')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'הגשה שבועית',
                'verbose_name_plural': 'הגשות שבועיות',
            },
        ),
        migrations.CreateModel(
            name='Shift1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, max_length=200, verbose_name='הערות')),
                ('seq_night', models.IntegerField(default=0, verbose_name='מ"ס רצפים לילה לצהריים')),
                ('seq_noon', models.IntegerField(default=0, verbose_name='מ"ס רצפים צהריים לבוקר')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'הגשה כללית',
                'verbose_name_plural': 'הגשות כלליות',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='תאריך')),
                ('title', models.CharField(max_length=30, verbose_name='כותרת')),
                ('text', models.TextField(blank=True, verbose_name='טקסט')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'פוסט',
                'verbose_name_plural': 'פוסטים',
            },
        ),
        migrations.CreateModel(
            name='ArmingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.CharField(default='', max_length=9, verbose_name='תעודת זהות')),
                ('shift_num', models.IntegerField(default=1, verbose_name='מספר משמרת')),
                ('time_in', models.TimeField(default=django.utils.timezone.now, verbose_name='זמן כניסה')),
                ('num_mags', models.IntegerField(default=2, verbose_name='מספר מחסניות')),
                ('hand_cuffs', models.IntegerField(default=6, verbose_name='אזיקים')),
                ('gun_case', models.IntegerField(default=6, verbose_name='פונדה')),
                ('mag_case', models.IntegerField(default=6, verbose_name='נרתיק')),
                ('keys', models.BooleanField(default=False, verbose_name='מפתחות')),
                ('radio', models.BooleanField(default=False, verbose_name='קשר')),
                ('radio_kit', models.BooleanField(default=False, verbose_name='ערכת שמע')),
                ('time_out', models.TimeField(blank=True, null=True, verbose_name='זמן יציאה')),
                ('signature_in', models.TextField(blank=True, null=True, verbose_name='חתימת כניסה')),
                ('signature_out', models.TextField(blank=True, null=True, verbose_name='חתימת יציאה')),
                ('read', models.BooleanField(default=False, verbose_name='טופל?')),
                ('reason', models.TextField(default='', verbose_name='סיבה')),
                ('gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mishmar.gun', verbose_name='מספר נשק')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mishmar.arming_log', verbose_name='הזנה ביומן חימוש')),
            ],
            options={
                'verbose_name': 'בקשה לשינוי יומן חימוש',
                'verbose_name_plural': 'בקשות לשינוי יומן חימוש',
            },
        ),
        migrations.AddField(
            model_name='arming_log',
            name='gun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mishmar.gun', verbose_name='מספר נשק'),
        ),
        migrations.AddField(
            model_name='arming_log',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='שם משתמש'),
        ),
    ]
