# Generated by Django 3.2.8 on 2022-02-07 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mishmar', '0002_auto_20220207_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationshift',
            name='index',
            field=models.IntegerField(default=1, verbose_name='מספר משמרת'),
        ),
        migrations.AlterField(
            model_name='week',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
