# Generated by Django 3.2.8 on 2022-02-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishmar', '0003_auto_20220207_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationshift',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='כותרת משמרת'),
        ),
    ]
