# Generated by Django 3.2.8 on 2022-02-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishmar', '0004_alter_organizationshift_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationshift',
            name='manager',
            field=models.BooleanField(blank=True, default=False, verbose_name='אחמש'),
        ),
        migrations.AddField(
            model_name='organizationshift',
            name='opening',
            field=models.BooleanField(blank=True, default=True, verbose_name='פתיחה'),
        ),
    ]
