# Generated by Django 3.2.8 on 2022-02-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishmar', '0006_alter_organizationshift_opening'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationshift',
            name='pull',
            field=models.BooleanField(blank=True, default=False, verbose_name='משיכה'),
        ),
    ]
