# Generated by Django 3.2.8 on 2022-02-08 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mishmar', '0008_settings1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
