# Generated by Django 3.2.8 on 2022-02-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mishmar', '0013_armingrequest_input_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitting', models.BooleanField(default=True, verbose_name='ניתן להגיש/לשנות הגשות')),
                ('pin_code', models.IntegerField(default=1234, verbose_name='קוד זיהוי')),
                ('officer', models.CharField(max_length=20, verbose_name='קצין מתקן')),
                ('city', models.CharField(max_length=100, verbose_name='עיר')),
                ('max_seq0', models.IntegerField(default=2, verbose_name='מספר רצפים מקסימלי לילה לצהריים')),
                ('max_seq1', models.IntegerField(default=2, verbose_name='מספר רצפים מקסימלי צהריים לבוקר')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='גרסה')),
                ('friday_morning', models.BooleanField(blank=True, default=False, verbose_name='שישי בוקר נחשב במינימום הגשות?')),
                ('friday_noon', models.BooleanField(blank=True, default=False, verbose_name='שישי בצהריים נחשב במינימום הגשות?')),
                ('num_mags', models.PositiveIntegerField(default=1, verbose_name='מספר מחסניות')),
                ('hand_cuffs', models.PositiveIntegerField(default=1, verbose_name='מספר אזיקים')),
                ('num_mag_cases', models.PositiveIntegerField(default=1, verbose_name='מספר פונדות')),
                ('num_gun_cases', models.PositiveIntegerField(default=1, verbose_name='מספר נרתיקים')),
            ],
        ),
    ]
