# Generated by Django 3.2.8 on 2022-02-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mishmar', '0014_settings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings1',
        ),
    ]
