# Generated by Django 3.2.8 on 2022-02-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mishmar', '0016_auto_20220212_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationshift',
            options={'verbose_name': 'משמרת מבנה סידור', 'verbose_name_plural': 'משמרות מבנה סידור'},
        ),
    ]
