# Generated by Django 3.2.8 on 2022-02-20 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mishmar', '0017_alter_organizationshift_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, max_length=200, verbose_name='הערות')),
                ('seq_night', models.IntegerField(default=0, verbose_name='מ"ס רצפים לילה לצהריים')),
                ('seq_noon', models.IntegerField(default=0, verbose_name='מ"ס רצפים צהריים לבוקר')),
                ('data', jsonfield.fields.JSONField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'הגשה כללית',
                'verbose_name_plural': 'הגשות כלליות',
            },
        ),
    ]
