# Generated by Django 3.2.8 on 2022-02-20 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mishmar', '0018_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift',
            old_name='data',
            new_name='weeks_data',
        ),
    ]
