# Generated by Django 3.2.8 on 2022-02-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mishmar', '0019_rename_data_shift_weeks_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'הגשה', 'verbose_name_plural': 'הגשות'},
        ),
        migrations.RemoveField(
            model_name='shift',
            name='date',
        ),
        migrations.AddField(
            model_name='shift',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mishmar.organization'),
        ),
    ]
