# Generated by Django 3.2.8 on 2022-02-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mishmar', '0023_rename_username_shift_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.RemoveField(
            model_name='shift1',
            name='username',
        ),
        migrations.RemoveField(
            model_name='shiftweek',
            name='username',
        ),
        migrations.DeleteModel(
            name='Week',
        ),
        migrations.DeleteModel(
            name='Shift1',
        ),
        migrations.DeleteModel(
            name='ShiftWeek',
        ),
    ]
